name: Compile Typst Notes and Release PDFs

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  compile-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Typst
      uses: typst-community/setup-typst@v3
      with:
        typst-version: latest
        
    - name: Install fonts
      run: |
        # Install Chinese fonts for proper rendering
        sudo apt-get update
        sudo apt-get install -y fonts-noto-cjk fonts-noto-cjk-extra
        
    - name: Find and compile Typst files
      run: |
        # Create output directory
        mkdir -p compiled-pdfs
        
        # Find all directories containing note.typ or practice.typ files
        find . -name "note.typ" -o -name "practice.typ" | while read -r file; do
          # Get the directory name
          dir=$(dirname "$file")
          dir_name=$(basename "$dir")
          
          # Skip template directory
          if [ "$dir_name" = "template" ]; then
            continue
          fi
          
          # Get the filename without extension
          filename=$(basename "$file" .typ)
          
          echo "Compiling $file in directory $dir_name"
          
          # Compile the file
          if typst compile "$file" "compiled-pdfs/${dir_name}-${filename}.pdf"; then
            echo "✅ Successfully compiled $file"
          else
            echo "❌ Failed to compile $file"
            exit 1
          fi
        done
        
        # List compiled files
        echo "Compiled files:"
        ls -la compiled-pdfs/
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: compiled-pdfs
        path: compiled-pdfs/
        retention-days: 30
        
    - name: Create Release (on tag push)
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: compiled-pdfs/*.pdf
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Create Development Release (on main branch push)
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: dev-${{ github.sha }}
        name: Development Build - ${{ github.sha }}
        files: compiled-pdfs/*.pdf
        generate_release_notes: true
        draft: false
        prerelease: true
        body: |
          This is an automated development release.
          
          **Commit:** ${{ github.sha }}
          **Branch:** ${{ github.ref_name }}
          **Triggered by:** ${{ github.event_name }}
          
          Contains the latest compiled PDF versions of all notes and practice files.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}